Joia!  Agora  vamos  voltar  à  definição  de   `texto-resumo-em-
yuan` :

```
(defn texto-resumo-em-yuan [transacao]
  (data-valor (transacao-em-yuan transacao)))
```

Esta  função  é  um  bom  caso  para  usarmos  a  macro   `thread-
first`  ( -> ),  já  que  a  função  nada  mais  faz  que  aplicar   `data-
valor`  aos dados retornados por  `transacao-em-yuan` :

```
(defn texto-resumo-em-yuan [transacao]
  (-> (transacao-em-yuan transacao)
      (data-valor)))
```

Mas  também  é  um  bom  exemplo  para  a  introdução  do
conceito de composição de funções!

=== 6.1 COMPOSIÇÃO DE FUNÇÕES

Se você se acostumou com a ideia de composição no mundo da
Orientação  a  Objetos,  aqui  é  parecido:  combinamos  funções  em
uma só, de modo que a aplicação de uma só função corresponda à
aplicação  de  várias.  Aqui,  quando  o  propósito  de  uma  função  é
apenas  combinar  outras  funções,  passando  para  uma  o  resultado
da  outra,  há  o  forte  indício  de  que  podemos  fazer  uso  da
composição  de  funções.  Existe  um  recurso  em  Clojure  que  nos
permite construir a composição de duas ou mais funções: a função
 `comp` . Usando  `comp , quer dizer, fazendo composição de  `data-
valor`   e   `transacao-em-yuan` ,   `texto-resumo-em-yuan`   fica
assim:

```
(def texto-resumo-em-yuan (comp data-valor transacao-em-yuan))

(map texto-resumo-em-yuan transacoes)
;; ("19/11/2016 => ¥ -70.950" ...
```