simplificar o entendimento do que uma função faz. Por exemplo,
para  juntar  elementos  de  um  array  em  uma  string,  com  os
elementos separados por vírgula, fazemos o seguinte:

```
(clojure.string/join ", " (map texto-resumo-em-yuan transacoes))
;; "19/11/2016 => ¥ -70.950, 01/12/2016 => ¥ +5805.000, ...
;;  03/12/2016 => ¥ -62.350"
```

`clojure.string/join`  significa que vamos aplicar a função
 `join`   que  se  localiza  no  namespace   `clojure.string` .  Esta
função recebe um argumento que diz qual o delimitador entre os
elementos  e  um  array.  Mas  usar   `clojure.string/join`  ",  " 
com  muita  frequência  é  bem  chato.  Ainda  bem  que  podemos
facilitar um pouco as coisas:

```
;; uma função parcial que juntará elementos em uma string,
;; separando-os por vírgula
(def juntar-tudo (partial clojure.string/join ", "))

(juntar-tudo (map texto-resumo-em-yuan transacoes))
;; "19/11/2016 => ¥ -70.950, 01/12/2016 => ¥ +5805.000, ...
;;  03/12/2016 => ¥ -62.350"
```

Neste  exemplo,    `juntar-tudo`    é  a  aplicação  parcial  de
 `clojure.string/join` ,  já  definindo  o  primeiro  argumento.  Os
demais argumentos vêm depois, quando a função parcial  `juntar-
tudo`   é  aplicada  ao  resultado  de   (`map`  `texto-resumo-em-yuan
transacoes`) .

=== 6.3 CONCLUSÃO

A  composição  de  funções  é  um  recurso  de  alto  potencial  em
Programação  Funcional,  com  baixo  custo  de  implementação,
tendo em vista que funções são cidadãs de primeira classe. É muito
útil  quando  temos  transformações  em  série  que  costumam  vir